### PR TITLE
Markdown character sheet - Evan

### PR DESCRIPTION
**Pull request by ecowden**
Meh.

I mean, it's got all the info, but you can scan it as well as a crinkled, scratched Snickers wrapper in the supermarket express lane.

I'm not going to merge without improving it. Suggestions welcomed!

### CODE REVIEW

**Comment by runicfox** [comment]
Oh, also - did you want to add your known spells?

**Comment by ecowden** [comment]
Great suggestions! Thank you! 

I've,

* Changed breath attack "area" to "line"
* Added Constitution bonus and Draconic Resilience modifier to hit dice
* Added spellcasting section, with spell lists and stats
* Added other misc info, like height, weight, etc.
* Miscellaneous formatting.

I'm still a bit uncertain about the spell lists. I tried to pick the attack spells that use fire, then pick up some other utility spells that might help in non-combat situations. There's probably some overlap with what Rinn will bring to the table as a trickster. Also: totally not sure that's even a good approach. Suggestions?

**Comment by runicfox** [comment]
With choosing spells, it's a hard balance to keep (especially at lower levels). A cleric can help with the non-combat spells to an extent. In some cases, the careful selection of certain cantrips (0-level spells) can make a huge difference when applied creatively.

Joanne will also need to get her character made tomorrow, so that will be a good time to discuss and decide.

**Comment by ecowden** [comment]
Cool. I'm going to go ahead and merge this sucker. Feel free to edit, open new issues, etc.

**Pull request merged**
