### PR TITLE
Adds PDF reference to animal companions

### PR DESCRIPTION
**Pull request by ecowden**
Full details on animal companions can be found in the free Basic DM Rules PDF. I added a link to the animal companion table.

The critters are near the end. I've generally been able to find them by just searching for the name of the one I want.

### CODE REVIEW

**Comment by ecowden** [comment]
Heads up: I also noticed that there were a bunch of critters in that PDF that weren't in the list. Anything with a challenge rating (CR) or 1/4 of less looks eligible. 

Happy choosing!

**Comment by runicfox** [comment]
Awesome!  Thanks for getting that link on there.  :+1:

**Comment by runicfox** [comment]
Just curious if this can be merged?

**Comment by ecowden** [comment]
Oh yeah! Sorry!

Merging...

**Pull request merged**
